To Do list: add & remove
Hisoka37/To-DO-List pull request #4
Opened 2023-02-23 20:42 UTC by Hisoka37

# To Do list: add & remove
 
![](https://media.giphy.com/media/Cmr1OMJ2FN0B2/giphy.gif)
 **In this PR I:**

- [ ] Create a new JavaScript file for the new functionality.
- [ ] Implement a function for adding a new task.
- [ ] Implement a function for deleting a task.
- [ ] Implement a function for editing task descriptions.
- [ ] Follow GitHub flow.
- [ ] Fix Linters errors.

_Happy Coding_ 😁

2023-02-23 22:14 UTC, Gambit142 requested changes
Hi @Hisoka37 👋, 

Good job so far!

## Highlights
- All linters checks passed ✔️ 
- README.md file ✔️ 

There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Kindly check the comments under the review._

### N.B: Due to compilation using `webpack`, I couldn't test his functionalities. Please, the next reviewer should take not of this and check it out. 👍 😎 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider:

N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### Please, remember to tag me in your question so I can receive the notification. You can tag me by typing @Gambit142

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-02-23 22:14 UTC, Gambit142 commented on src/modules/main.js
> +}
- [x] Remember that each task's `index` property should be equal to the length of the current array. This means that the `index` property of the first _**task**_ should be `1`, that of the second task should be `2` and so on. When looping through arrays in JavaScript, the `index` of the first item in the array is `0`. Therefore, the way you are updating the indexes would be incorrect. I would advise you to set it to `index + 1`. 👍 😎

2023-02-23 22:14 UTC, Gambit142 commented on src/modules/main.js
> +      index: tasks.length,
- [x] Remember that each task's `index` property should be equal to the length of the current array. This means that the `index` property of the first _**task**_ should be `1`, that of the second task should be `2` and so on. Currently, the numbering of the tasks index will start from `0` if there are no items in the `localStorage`. Kindly set the index property to `tasks.length + 1` 👍 😎

2023-02-23 22:14 UTC, Gambit142 commented on src/modules/main.js
> +  }
- [ ] When I start your application using npm run serve, I get this error in the console of the browser 

![image](https://user-images.githubusercontent.com/77106962/221040663-455a8c54-0cff-4ccb-8917-a487c7abb6d1.png)

I couldn't add tasks, delete or edit tasks because `webpack` was not compiled properly. I would suggest that you compile `webpack` properly and pay attention to the way you set it up in the `webpack.config.js` file. Also, pay attention to the `output` key in the `module.export` object. 👍 

![chrome-capture-2023-1-23 (1)](https://user-images.githubusercontent.com/77106962/221042405-25cf506f-d93f-45ce-a529-de09c59c046b.gif)

2023-02-23 22:25 UTC, Hisoka37 commented on src/modules/main.js
> +  }
Hello @Gambit142 🙌, The server works fine on my side I test it with two browsers and it's working fine.
I don't know what I should do now.

2023-02-23 22:33 UTC, Hisoka37 commented on src/modules/main.js
> +  }
The problem is the Enter key doesn't submit the task you must click on the add button. can you try it and let me know if it's the problem, please?

2023-02-24 08:42 UTC, codepantha approved these changes
# STATUS: CHANGES REQUIRED ♻️ 

## Hi @Hisoka37 👋, 

Well done for implementing the required changes 👏 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media2.giphy.com/media/2RGhmKXcl0ViM/giphy.gif"/>

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-24 09:11 UTC, merged